### ISSUE TITLE
学习了，请教一下demo里databinding的按钮点击事件如何添加防抖双击

### ISSUE THREAD

**Issue by abcdisgreat** [KunMinX/Jetpack-MVVM-Best-Practice#1]

**Comment by KunMinX** [comment]
其实很简单，
在 statusViewModel 中配置一个 ObservableBoolean 用于管理按钮的禁用状态，
并在 button xml 元素的 enabled 属性中绑定这个 vm.enabled，
而判断是否在点击后禁用的 UI 逻辑，仍然沿用之前你在用的判断逻辑即可。

**Comment by KunMinX** [comment]
@abcdisgreat 
androidCodeUtil 库 新增了 ClickUtil ，里面有双击防抖的功能，是基于 AOP 的实现，感兴趣可以尝试下
