### ISSUE TITLE
关于网络请求

### ISSUE THREAD

**Issue by alextyloo** [KunMinX/Jetpack-MVVM-Best-Practice#10]
我在OKHttp build中使用到持久化Cookie，所以在build过程中需要用传入Context ,那么我在ViewModel请求网络过程中也要传入Context,  这样好像违背了MVVM..不知道该如何解决

**Comment by KunMinX** [comment]
@alextyloo 不建议通过 ViewModel 传入 context，可以通过别的方式获取 Application 级的 context，如此可避免内存泄漏。
具体可参考 AndroidCodeUtils 中通过 Utils 类 获取 app 级 context 的办法

**Comment by looogen** [comment]
我也感觉到了，看来也只能这样去获取了。
