### ISSUE TITLE
Navigation 启动新页面并关闭当前页面的功能如何实现？

### ISSUE THREAD

**Issue by wflian** [KunMinX/Jetpack-MVVM-Best-Practice#101]
比如先登录后使用的应用！  登录页面 LoginFragment 里面的登录按钮，登录成功以后 打开 MainFragment 并关闭 LoginFragment。这情况如何实现呢？

**Comment by KunMinX** [comment]
login 页先 navigateUp，main 页再进入。具体自己尝试了
