### ISSUE TITLE
我认为你的代码没有参考价值(I don't think your code has any reference value)

### ISSUE THREAD

**Issue by qcks** [KunMinX/Jetpack-MVVM-Best-Practice#11]
看到了许多陷阱，和老旧的写法，如果有意义README.md里面应该就不是gif了，至少要面向组件化方向吧，但没有看到影子。总的来说不如去https://developer.android.google.cn/jetpack/ 随便看看收益高，因为别人的代码都是狗屎(Everyone else's code is shit)

**Comment by KunMinX** [comment]
网络上你对我代码重拳出击，现实里你刚上初一 …
