### ISSUE TITLE
ShareViewModel的一些疑问

### ISSUE THREAD

**Issue by joeye-io** [KunMinX/Jetpack-MVVM-Best-Practice#126]
作者你好，这套框架非常好，有很多值得思考的地方。
不过有个疑问，假设有一模块既不是Activity也不是Fragment的域使用到ShareViewModel的数据时，应该如何获取会是比较好的方案呢？

**Comment by KunMinX** [comment]
根据你提供的信息，很难让人帮到你

**Comment by yeweicong** [comment]
不好意思

这里其实我的想法是一些内存间跨页面，跨模块共享的实体使用ShareViewModel存储。例如用户信息实体，我希望在全应用任何地方共享这个统一的数据源。
那这里遇到一些问题，如果我的使用地方是okhttp的拦截器Interceptor中使用到这个用户信息实体，它不属于activity/fragment的使用位置，那应该是通过什么样的方式获取这个ShareViewModel中保存的用户信息实体呢？

不知道这么说能不能表达出本意...

**Comment by KunMinX** [comment]
ViewModel 的用途是，方便在页面元素的环境发生变化时（例如旋转屏幕），保留临时状态信息，避免重新请求数据造成额外消耗，

okhttp 属于数据操作，不建议使用 sharedViewModel 托管。通常是单例等方式托管。

**Comment by joeye-io** [comment]
明白 感谢~
