### ISSUE TITLE
Cannot add the same observer with different lifecycles

### ISSUE THREAD

**Issue by zbyJade** [KunMinX/Jetpack-MVVM-Best-Practice#13]
我使用了您的BaseActivity，有多个Activity都继承了BaseActivity，我在使用的时候报错
 java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles
找到原因代码
   NetworkStateManager.getInstance().mNetworkStateCallback.observe(this, netState -> {
            //TODO 这里可以执行统一的网络状态通知和处理

        });
如果有多个Activity，如何正确的使用BaseActivity呢

**Comment by KunMinX** [comment]
@zbyJade 网络状态回传的这段逻辑，我还要再斟酌一下，不排除将来直接留给子类去操作，以规避 liveData 对唯一性的考虑。
具体缘由可见上一个 issue。

https://github.com/KunMinX/Jetpack-MVVM-Best-Practice/issues/12

**Comment by zbyJade** [comment]
好的

**Comment by KunMinX** [comment]
@zbyJade 
找到引发这个现象的根源的根源了，是 lambda 导致。lambda 中不可空实现，否则会被认为是同一个 Observer，
代码已更新，缘由详见：

https://stackoverflow.com/questions/47025233/android-lifecycle-library-cannot-add-the-same-observer-with-different-lifecycle
