### ISSUE TITLE
底部播放器提示风险警告水印:”PlayerFragment 未遵循 Databinding 严格模式，存在 null 安全风险“

### ISSUE THREAD

**Issue by wobuaimxd** [KunMinX/Jetpack-MVVM-Best-Practice#131]
作者你好，将项目加载到手机上后，布局 fragment_player 左上角出现不可消除的警告提示:”PlayerFragment 未遵循 Databinding 严格模式，存在 null 安全风险“。拆解后，应该是 PlayerFragment.java 中调用 (FragmentPlayerBinding) getBinding()，所致。请问使用系统生成的 databindingimpl 操作控件就会出现此警告吗，并且这种水印应该怎么消除呢，多谢。

**Comment by KunMinX** [comment]
debug 模式下会提示，方便开发者觉察和遵循。release 模式下不会提示。

**Comment by wobuaimxd** [comment]
好的，谢谢。我改成 release 后提示消失了。

这边还想问一个问题，就是在播放器视图展开后，title 最终显示位置没有正好居中，实际会偏左边一点，这个对于长度越短的 title 表现越明显。

code：titleEndTranslationX = (screenWidth / 2) - (titleWidth / 2) - DisplayUtils.dp2px(67);

**Comment by KunMinX** [comment]
是有这个问题。感兴趣可自行修改

**Comment by wobuaimxd** [comment]
我知道了，因为 PlayerSlideListener 只在初始化时对 titleEndTranslationX 计算一次，所以之后所有的 article 都只按照第一次计算的 titleEndTranslationX 计算最终位置。按此逻辑修改代码即可，谢谢。

**Comment by wobuaimxd** [comment]
在 onPanelSlide 加入 calculateTitleAndArtist(); title 和 artist 即可正常居中显示。

**Comment by KunMinX** [comment]
感谢你的反馈。

另外在歌曲切换时，标题同样需要重新计算位置，我们在 playerFragment 的 PlayerManager 歌曲切换事件监听中，添加了如下代码

```java
PlayerManager.getInstance().getChangeMusicEvent().observe(getViewLifecycleOwner(), changeMusic -> {

            ......

            if (mListener != null) {
                view.post(mListener::calculateTitleAndArtist);
            }
        });

```

**Comment by wobuaimxd** [comment]
好的，能帮上忙真是太好了。
