### ISSUE TITLE
下载模拟显示问题

### ISSUE THREAD

**Issue by KunLL** [KunMinX/Jetpack-MVVM-Best-Practice#141]
我这边在模拟器里测试这个返回仍然在下载的界面
         SearchFragment
        点开“测试下载，返回页面仍有效”按钮，进度条开始动，然后我重复退出进入SearchFragment，就会发现离开页面终止的那个进度条也有数据了
        Debug断点打在getDownloadFileCanBeStoppedLiveData里，复现这个问题，但是并没有断点，很奇怪。
        换成真机到是没有出现过这个问题

**Comment by KunMinX** [comment]
过去也有过类似反馈。建议使用真机测试。不然缺乏可复现信息，难以核对。
