### ISSUE TITLE
PlayerFragment does not follow the DataBinding strict mode, there is a Null security risk of view calls. 

### ISSUE THREAD

**Issue by zinwalin** [KunMinX/Jetpack-MVVM-Best-Practice#149]
![image](https://user-images.githubusercontent.com/5416196/177485274-082fa09b-9b9e-4f6c-8f30-4f54e1c047b2.png)

**Comment by KunMinX** [comment]
Yes, it is deliberately done here to show the prompt when the strict mode is not followed
