### ISSUE TITLE
能否解决navigation args在多个模块传数据的问题？

### ISSUE THREAD

**Issue by AweiLoveAndroid** [KunMinX/Jetpack-MVVM-Best-Practice#188]
如题。
跨模块使用navigation agrs 需要维护多套navigation.xml 而且发送和接收的要保持一致。每个模块都要写一遍很麻烦。如何优化？

**Comment by KunMinX** [comment]
没懂你的需求哈。
google 封装 navigation 框架，主要侧重于提供可视化预览，在跨模块支持上有所欠缺。
换言之如不是很需要可视化预览，未必需要使用 navigation。
跨模块跳转和通信，建议是使用 ARouter 等专职这类需求的框架，然后将具体页面间的跳转，统一写在公共模块供所有模块调用，以消除多模块代码修改时的不一致。
