### ISSUE TITLE
不建议直接暴露liveData的写操作

### ISSUE THREAD

**Issue by ChillingVan** [KunMinX/Jetpack-MVVM-Best-Practice#2]
https://github.com/KunMinX/Jetpack-MVVM-Best-Practice/blob/f7fac5071611d46a8913ec5345fe824d55c78393/app/src/main/java/com/kunminx/puremusic/ui/page/PlayerFragment.java#L118

项目看到ViewModel类只单纯持有liveData，且直接暴露liveData。
比较好的一种写法是添加Model层，例如XXXRepository或XXXModel。
所有对liveData的写操作都通过ViewModel调用Repository来写。
暴露的liveData只调用observe方法。
不然写操作多的话，遍地的liveData的set会导致很难维护。

可能项目里liveData数据结构简单所以感知不是特别大。

**Comment by KunMinX** [comment]
@ChillingVan 

你好，请 认真阅读源码 和 注释 再作评论。代码中 根本不存在 你提到的状况。

首先，ViewModel 根据作用，存在三种状况。
我在 callback、request、status 包下，分别准备了三种作用的 ViewModel。
你说的 ViewModel 是指 request 这种。

其次，你所见到的直接暴露的，并不是 liveData，而是 DataBinding 视图绑定用的 ObservableField。它们负责作为 UI 逻辑末端的、通过数据驱动来通知视图改变状态，而不负责数据的请求和响应。

最后，每个视图控制器都配套一个专属的 StatusViewModel，专门负责管理 视图控制器内部视图的状态。

**Comment by ChillingVan** [comment]
那假如要把seekPosition每次的变化打log，该如何加代码呢？

**Comment by KunMinX** [comment]
@ChillingVan 
在经过长时间的磨合后，我们决定直接在 statusViewModel 中使用 public final 的可观察数据，而在 视图控制器中来设置和观察 log。
因为 statusViewModel 我们几乎不会去关顾，只是纯粹的托管用途，使用 public final，意在表明它的绝对纯粹，以免团队中的新手在 statusViewModel 中添加任何逻辑（从而导致后续其他人的疏忽）

当然你的愿望是通过 getter、setter 来实现更好的拓展性，这些在 requestViewModel 中都有体现。

**Comment by ChillingVan** [comment]
不大明白，搜了一下requestViewModel ，没看到有可以给seekPosition打log的地方喔

**Comment by KunMinX** [comment]
@ChillingVan 
我们不会在 statusViewModel 添加任何逻辑，以免被疏忽。
seekPosition 属于视图的状态，其数据的来源来自 liveData。如需 log，在 视图控制器中编写即可

**Comment by ChillingVan** [comment]
所以打个log要observe？

**Comment by KunMinX** [comment]
@ChillingVan 
牛头不对马嘴的抬杠，叫人怎么回复？

**Comment by ChillingVan** [comment]
不是，你就直接说你这里的代码该如何加seekPosition的log，不大理解你说的视图控制器是啥

**Comment by KunMinX** [comment]
@ChillingVan 
seekPostion 这些数据都来自 唯一可信源统一推送，这在代码里没有详细注释过吗？
正因为要通过 唯一可信源来接收数据、避免数据的滥发、事件源的不可追溯，所以才需要在 liveData.observe 中观察。
所以在 liveData.observe 中打 log 很难吗？
Activity 和 Fragment 都是视图控制器，有什么问题吗？

恕我直言，我只为愿意思考、有在思考的读者负责，我不想为 这种凡事凭感觉、只想着技术来适应自己、却从不想去 认识和理解技术的人 花时间。

**Comment by ChillingVan** [comment]
这么说吧，liveData set并不一定会触发observe的onChange。
只是讨论问题却人身攻击，真是服了。还是别误人子弟了吧

**Comment by KunMinX** [comment]
seekPostion 这些数据都来自 唯一可信源统一推送，这在代码里有着详细的注释。
正因为要通过 唯一可信源来接收数据、避免数据的滥发、事件源的不可追溯，所以才需要在 liveData.observe 中观察。
Activity 和 Fragment 都是视图控制器。

DataBinding 和 LiveData 都分不清 就急着信口开河、指点江山，我只能帮到这儿了。

**Comment by Techvisionbest** [comment]
> @ChillingVan
> 
> 你好，请 认真阅读源码 和 注释 再作评论。代码中 不存在 你提到的状况。
> 
> 首先，ViewModel 根据作用，存在三种状况。
> 我在 callback、request、status 包下，分别准备了三种作用的 ViewModel。
> 你说的需要分层调度数据的 ViewModel 是指 request 这种，这在 MusicRequestViewModel 和 InfoRequestViewModel 中有详细的范例。
> 
> 其次，你所见到的直接暴露的，并不是 liveData，而是 DataBinding 视图绑定用的 ObservableField。它们负责作为 UI 逻辑末端的、通过数据驱动来通知视图改变状态，并不负责数据的请求和响应。
> 
> 最后，每个视图控制器都需要配套一个专属的 StatusViewModel，专门负责管理 视图控制器内部视图的状态。

您好，请问下，类似于发起网络请求展示网络请求结果的这种页面，看到您说的“每个视图控制器都需要配套一个专属的 StatusViewModel，专门负责管理 视图控制器内部视图的状态”，意思就是除开StatusViewModel外，应该还有用于业务逻辑请求网络数据的ViewModel么？这个StatusViewModel是用来控制页面的Loading、Error状态的么？如果是的话，那这个StatusViewModel如何正确的切换自己的状态呢？

**Comment by KunMinX** [comment]
@Techvisionbest 
请直接阅读最新源码。
在和热心读者的交流后，目前架构已演化出 domain 层，viewModel 专职于状态托管，关于请求等操作后移至 domain 层的 request 以方便组合和复用。
