### ISSUE TITLE
在框架基础上实现稍微复杂的示例

### ISSUE THREAD

**Issue by 751811032** [KunMinX/Jetpack-MVVM-Best-Practice#21]
有没有在此框架基础上实现的稍微复杂一点的示例。可以更好的学习该架构

**Comment by KunMinX** [comment]
MVVM 的目标是通过 数据驱动编程 来实现 解耦的、关注点分离的 软件开发模式。
Jetpack MVVM 是在 MVVM 模式的基础上引入了 软件工程安全 以及 用户体验优化 的设计。
因此 Jetpack MVVM 的边界目前仅限于 LifeCycle、LiveData、ViewModel、DataBinding 这四样。（时下的公司比较重视对前三者的正确理解和使用）
·
DataRepository 是数据层的一种组织方式，并不是开发组件，也不存在于 Jetpack 架构组件中，它隐含的思想是 通过组合模式，来方便对 本地数据源 或 远程数据源 的灵活组合和对 UI 层的结果输送。为了点到为止地 为读者确立 MVVM 的边界，最佳实践中暂时没有过多地拓展 DataRepository 的代码。
·
此外，DataRepository 层使用到的 Room 等组件，比较简单，确定仅看官方文档就能轻松上手（建议首先通过深度思考 确立 SQL 的场景和用途本身，再上手具体的 Room 使用）。
https://developer.android.google.cn/training/data-storage/room/index.html
