### ISSUE TITLE
对ViewModel的一些疑惑

### ISSUE THREAD

**Issue by looogen** [KunMinX/Jetpack-MVVM-Best-Practice#22]
- ClickProxy能不能写在VM,我直接设置liveData值，然后试图控制器里去观察是不是也可以呢？
- Model应该只能VM去引用吧？那这样的话，视图控制器直接去观察ModelliveData,这样有没有违背这个原则。比如在 MainFragment onViewCreated
`PlayerManager.getInstance().getChangeMusicLiveData().observe()`

> 期待解答传道 :），感谢!

**Comment by KunMinX** [comment]
@looogen 
MVVM 两大特性是 数据驱动 和 关注点分离，
UI 层就做 UI 的事，数据层就做业务的事，VM 是中间桥梁，做承上启下转发的事。
ViewModel 如此设计，主要是为了满足 单向依赖 以避免 内存泄漏。
LiveData 放在视图控制器中观察，是必然的结果，因为 MVVM 框架只是 UI 框架，如果 LiveData 放在 ViewModel 中观察，那么回调中势必只能操作 ViewModel 中的成员、通过 DataBinding 来驱动视图变化，
那么对于非视图绑定的成员，LiveData 的观察回调中该怎么办呢？因为 ViewModel 的核心目标是服务于 View 的状态，而不适合托管视图控制器的成员，并且也不可以反向去调用视图控制器的成员（否则就破坏了单向依赖，埋下内存泄漏的隐患），
综上，UI 逻辑务必 UI 中写，LiveData 回调属于 Ui 逻辑处理，应在 Ui 中观察。

更多关于 ViewModel 中不适合写逻辑的解析，可见 https://github.com/KunMinX/Jetpack-MVVM-Best-Practice/issues/7  3 楼。

**Comment by looogen** [comment]
>感谢迅速的回答，我又有了新的认识，特别是“viewmodel只负责view状态不负责控制器的成员”这一点，issue基本我都看过了，我还是有疑问：
- 在视图控制器中观察这一点没毛病，我纠结的是视图控制器直接通过model层去获取livedata，我的理解是应该通过viewmodel到model层获取然后返回给视图控制器以观察。不知道是不是我对依赖的理解有误。
- 对于Click交互事件可以看作都是一些UI逻辑处理，所以必须放在控制器，然后去改变viewmodel相关view状态的值。我对于这点的理解是这样的。这样对吗？

**Comment by KunMinX** [comment]
@looogen 
是这样的，在《最佳实践》项目中可见，对于需要向 数据层获取数据的情况，都是在视图控制器中通过 bridge.request 包下的 request-ViewModel 去间接获取，视图控制器本身不能直接接触 数据层。

是的，如果是 DataBinding 使得 ViewModel 持有的数据与布局控件属性发生绑定，那么即是在 视图控制器中调用 ViewModel 的数据，set 新值，以通知视图重绘。

- - - 

刚刚从床上翻身起床回复这条信息，是因为想起了一个十分简洁但重要的线索，即，目前为止 LiveData 只允许传入 LifecycleOwner 作为观察者，目前只有 Activity/Fragment 等 实现了 LifecycleOwner，而 ViewModel 不是。所以从某种角度也可说明，使用 LiveData 可以将与 UI 相关的通信限制在 UI 的领域中，避免向外泄露造成污染 ~

**Comment by looogen** [comment]
对头。项目很好，受益匪浅。

**Comment by looogen** [comment]
对头。项目很好，受益匪浅。
