### ISSUE TITLE
两个Activity如何共用一个ViewModel？

### ISSUE THREAD

**Issue by xueqi-pki** [KunMinX/Jetpack-MVVM-Best-Practice#233]
现在有两个页面：StaffDetailActivity和StaffEditActivity。
我在StaffDetailActivity用getActivityScopeViewModel(StaffFormState.class)为state赋值，在StaffEditActivity中如何取到同一个state对象？

**Comment by KunMinX** [comment]
使用 getApplicationScopeViewModel，获取 Application 级作用域的 viewModel 实例。
