### ISSUE TITLE
Audio焦点没有控制好，当puremusic在播放的时候，播放网易云音乐，puremusic失去焦点后，会再次抢走

### ISSUE THREAD

**Issue by LoveqLRC** [KunMinX/Jetpack-MVVM-Best-Practice#24]

**Comment by KunMinX** [comment]
@LoveqLRC 
感谢反馈。
考虑到 以播放记录的分发为例 能够方便介绍 LiveData 的存在缘由，故而选了音乐播放作为例子。
事实上，我本人对音乐感知不强，考虑不周实属遗憾。
Audio 焦点控制属于 User Interface 元素，因而源码被放置在 app module 的 player 包下，可供人们自由修改。
所以对于非可视化的用户接口控制，如有好的修改方案，可自行推送，我看到了会予以合并。
