### ISSUE TITLE
Kotlin 能適用嗎?

### ISSUE THREAD

**Issue by zihjielitw** [KunMinX/Jetpack-MVVM-Best-Practice#25]
請問是否有針對 Kotlin 版本的 Jetpack-MVVM-Best-Practice?
謝謝

**Comment by KunMinX** [comment]
@zihjielitw kotlin 完全适用。
为了更好地方便读者理解背景状况，目前一律使用 java 来构造 jetpack mvvm。
如需 kotlin，可在熟悉 jetpack mvvm 后，自行根据 kotlin 的语言特性来对该项目代码进行微调。
