### ISSUE TITLE
期待加入 SavedStateHandle

### ISSUE THREAD

**Issue by imknown** [KunMinX/Jetpack-MVVM-Best-Practice#27]

**Comment by KunMinX** [comment]
@imknown

感谢期待。本项目主要专注于 Jetpack MVVM 的几大架构组件，旨在方便开发者无痛理解它们的存在缘由、职责边界 和 高频适用场景。
SavedStateHandle 属于更大的 jetpack/AndroidX 范畴，未来我们可能单独起一个项目来介绍这些。
