### ISSUE TITLE
请问在这个框架中请求dialog在怎么添加比较合适呢

### ISSUE THREAD

**Issue by XuTongHuai** [KunMinX/Jetpack-MVVM-Best-Practice#28]

**Comment by KunMinX** [comment]
@XuTongHuai 

按以往的方式直接添加就行，可以看做与 Activity/fragment 地位平等的视窗

**Comment by XuTongHuai** [comment]
按照mvvm的规范来说，我们把数据的逻辑处理放在repository里面去处理，我现在是定义一个静态变量livedata，在BaseActivity中去监听其变化而进行dialog的显示和关闭，在repository中去postvalue()，这种方法是否合适呢

**Comment by KunMinX** [comment]
@XuTongHuai 
问题不大，不要反向依赖造成内存泄漏即可。
可以参考本项目中对 networkStateManager 的用法
