### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yutf99** [KunMinX/Jetpack-MVVM-Best-Practice#29]
应该是appcompat版本问题，看错题提示是webview报错了

**Comment by KunMinX** [comment]
@yutf99 
请提供一下操作路径，目前无法复现你说的闪退现象

**Comment by KunMinX** [comment]
@yutf99 
刚刚有小伙伴反馈了。你可 pull 到最新源码看看，昨天最新的更新解决了。
闪退可能是 event 未被消费导致的重复推送导致的。
