### ISSUE TITLE
wrong link for playstore

### ISSUE THREAD

**Issue by ze0** [KunMinX/Jetpack-MVVM-Best-Practice#3]
The link for the playstore is the same as the link for coolapk in the Readme File on line 83
`[![google-play1.png](https://upload-images.jianshu.io/upload_images/57036-f9dbd7810d38ae95.png)](https://www.coolapk.com/apk/247826) `

**Comment by KunMinX** [comment]
@ze0 
Thanks for your feedback, and it will soon be deal with.
