### ISSUE TITLE
想知道怎么在列表中增加多种样式的item

### ISSUE THREAD

**Issue by wangyuebanzi** [KunMinX/Jetpack-MVVM-Best-Practice#31]
目前adapter中关于ViewDataBinding的泛型其实是对应着holder的布局（因为holder在进行绑定的ui的时候会使用到此ViewDataBinding），假如一个列表中存在多种holder那该怎么处理ViewDataBinding的问题呢

**Comment by KunMinX** [comment]
@wangyuebanzi 
可以试试 drakeet 的 multiType adapter，试着将该库的 itemViewBinder 封装为基于 DataBinding 的通用 viewBinder 即可。
