### ISSUE TITLE
关于Navigation

### ISSUE THREAD

**Issue by painsky** [KunMinX/Jetpack-MVVM-Best-Practice#32]
看您的项目，从MainFragment->LoginFragment，的确MainFragment没有走onDestoyView
但是小的copy了architecture模块下navigation.fragment整个包到新项目，从
AFragment->BFragment，A就发生了onDestoryView。我看了下路由没啥异，是要有什么额外的设置才能让A不销毁视图吗？很疑惑，望解答

**Comment by KunMinX** [comment]
@painsky 
请移除自己项目中引入的 navigation.fragment gradle 引用，不然可能会覆盖来自 archi module 下的那些。

**Comment by skyshenfu** [comment]
@KunMinX  感谢您的建议，也反编译看了下 果然最后打进去的不是修改后的那个包，已解决问题不胜感激

**Comment by KunMinX** [comment]
@skyshenfu 
👍👍👍

**Comment by painsky** [comment]
您好，已经解决了问题 多谢

**Comment by helloworld10010** [comment]
如果移除`androidx.navigation:navigation-fragment-ktx`，`navArgs()`什么的好像就不能用了，我把仿造的包名改了，直接导入自己路径下navhost
