### ISSUE TITLE
BaseActivity getBinding的疑问🤔️

### ISSUE THREAD

**Issue by ouyuan2019** [KunMinX/Jetpack-MVVM-Best-Practice#34]
看到注释 子类警惕使用getBinding获取view实例，如果需要对view做一些动画操作，那需要如何处理比较好一些呢？

**Comment by KunMinX** [comment]
@ouyuan2019 
好问题。属性动画正面临着软工安全问题。后续考虑采用 motion 动画来规避。

**Comment by ouyuan2019** [comment]
@KunMinX 感谢回复，很期待您之后的文章

**Comment by KunMinX** [comment]
@ouyuan2019 
感谢期待，同时可关注 Jetpack-Missionary 新开辟的 motion 动画专题 😉
https://github.com/Jetpack-Missionary/MotionChallenge
