### ISSUE TITLE
基类抽取公共的ui及逻辑应该怎么做呢

### ISSUE THREAD

**Issue by hi2hcs** [KunMinX/Jetpack-MVVM-Best-Practice#38]
你好，请问下如果想在基类抽取公共的ui及对应的逻辑该怎么做呢？（像返回，title这种）

**Comment by KunMinX** [comment]
@hi2hcs 

这个我无法替你做主，可根据实际需求自己做决定。

此前一位小伙伴开源了自己的页面导航（标题栏、页面载入状态）方案，我推介给你

https://github.com/OpenBug-Android/OpenBug-Android#ymdhhjz
