### ISSUE TITLE
怎么理解状态管理分治

### ISSUE THREAD

**Issue by hanshengjian** [KunMinX/Jetpack-MVVM-Best-Practice#41]
请问这句话“MVP 的 Presenter 和 MVVM - Clean 的 ViewModel 都不具备状态管理分治的能力”怎么理解

**Comment by KunMinX** [comment]
@hanshengjian 

Jetpack ViewModel 考虑到并实现了在 Activity 环境配置变化（例如旋屏）导致的页面重建时，对页面成员变量的保存和恢复，

Presenter 和 mvvm-clean 版的 ViewModel 没有这一设计。

**Comment by hanshengjian** [comment]
理解了，我看了下配置发生变化时保存的具体对象是viewModelStore，这个对象具体activity的属性，它有个属性mMap,存储了所有的viewModel，通过ViewModelProvider.get()方法时，先获取最后配置变化的viewModelStore，然后从mMap中获取viewModel.理解了这个原理，也有一个小想法，就是viewModelStore是activity的对象，配置发生变化时，因为viewModelStore被保存下来了，所以旧的activity回收不了，感觉也是一个内存泄漏.

**Comment by hanshengjian** [comment]
理解了，我看了下配置发生变化时保存的具体对象是viewModelStore，这个对象具体activity的属性，它有个属性mMap,存储了所有的viewModel，通过ViewModelProvider.get()方法时，先获取最后配置变化的viewModelStore，然后从mMap中获取viewModel.理解了这个原理，也有一个小想法，就是viewModelStore是activity的对象，配置发生变化时，因为viewModelStore被保存下来了，所以旧的activity回收不了，感觉也是一个内存泄漏.

**Comment by KunMinX** [comment]
非也，配置发生变化时，仍然是基于同一个 Activity 实例，不然就谈不上对已保存状态的恢复了。

对 Activity 自身来说只是重走了一次生命周期流程，具体需结合实际场景理解。
