### ISSUE TITLE
想请教一下 PlayerFragment 的正确写法应该是怎样的呢 ？

### ISSUE THREAD

**Issue by RamboPan** [KunMinX/Jetpack-MVVM-Best-Practice#45]
看了一下 issue ，貌似没人提这个问题 ……

如果按照打开抽屉栏相同的思路（MainActivity 与 MainFragment 使用 SharedViewModel 进行信息传递），那 PlayerFragment 滑动时控件的移动应该是  （MainActivity 与 PlayerFragment 使用 SharedViewModel 进行信息传递）。

可以做一个 EventHandler 实现 SlidingUpPanelLayout.PanelSlideListener ，在 MainActivity 中将观察到的滑动百分比记录给 SharedViewModel ，在 PlayerFragment 中对 SharedViewModel 该百分比进行观察，对应调整 PlayerFragment 中控件的位置或透明。

如果不在 PlayerFragment 中使用 getBinding() 方法获取 viewBinding ，那应该如何初始化工程中 PlayerSlideListener 这个类呢 ？

感觉也可以将每个需要改变的控件做一个 BindAdapter 方法，将单个控件与观察到的百分比在 layout/fragment_player 中进行绑定，但有些时候要考虑父View 的大小；PlayerSlideListener 中还有个 mStatus （当然这个可以放在 PlayerFragmentViewModel 中），总体来说这样肯定不如写成一个类 PlayerSlideListener 整体控制好一点。

所以想知道下规范的写法，这里应该是怎样的 ？

**Comment by KunMinX** [comment]
@RamboPan 

DataBinding 严格模式主要是为了彻底规避 getBinding 的使用，而尽可能将与 "对视图实例的调用“ 相关的操作都限制在 xml 中，透过数据绑定来通知。

目前为止解决 “传统属性动画获得和修改属性” 的出路之一是 “Motion 动画”，转场过程 100% 可以在 xml 中完成、无需额外编写转场逻辑代码，唯一遗憾的是，motion 动画不支持 “控件同时获得 click 和 swipe 的手势”，并且考虑到对 getBinding 的隐患起个警示作用，目前项目中暂未使用 motion

（但我私下尝试过 **motion 动画，100% 确定可用于 ”视图调用 null 安全“ 的动画转场**，感兴趣可参见 motionChallenge 中的录屏，图二即是 motion 动画编写的结果，支持 swipe 手势上拉和下拉 https://github.com/Jetpack-Missionary/MotionChallenge）

**Comment by RamboPan** [comment]
感谢大佬指点，我先瞅瞅，如果没有啥疑问，我会2天内把这个关闭。
