### ISSUE TITLE
一加8pro安装demo出现中间绿色tab被遮挡的问题

### ISSUE THREAD

**Issue by OwnerKobe** [KunMinX/Jetpack-MVVM-Best-Practice#46]
![14FE3BA1FDF432E68271E2DC7A745877](https://user-images.githubusercontent.com/49399829/99395315-32ea3e00-291b-11eb-8653-e15bdbfbe2b8.jpg)

**Comment by OwnerKobe** [comment]
![14FE3BA1FDF432E68271E2DC7A745877](https://user-images.githubusercontent.com/49399829/99395400-51e8d000-291b-11eb-90ea-294b1d611741.jpg)

**Comment by OwnerKobe** [comment]
经过检查，在fragment_main.xml中139行 android:fitsSystemWindows="true" 之句话会对该机型造成此bug

**Comment by KunMinX** [comment]
@OwnerKobe 

感谢你的反馈。
考虑到本项目的目标是提供架构组件的示例代码，故而暂不对此做适配。
与此同时，市面上的软件对该 api 的使用十分普遍，如有意，请及时与一加开发者社区联系。
