### ISSUE TITLE
netStateEvent的问题

### ISSUE THREAD

**Issue by ouyuan2019** [KunMinX/Jetpack-MVVM-Best-Practice#48]
一个request里如果有多个请求，每个请求都设置里netStateEvent。但是每个请求对netStateEvent的结果处理不一样，这样就会有问题。比例一个需要根据state显示dialog，一个需要根据state显示loading。

**Comment by KunMinX** [comment]
@ouyuan2019 

感谢你的反馈，本项目主要专注于提供架构组件本身的示例，网络请求这块 后续会找个时间在新的示例 demo 中改进

**Comment by KunMinX** [comment]
@ouyuan2019 

已在最新版的代码中将 netStateEvent 的设计移除，
并且考虑到语义理解的方便，现采取直接将 DataResult 返回给 UI 层，
一来 UI 层便有机会根据 DataResult 的 resultState 针对请求成功和失败提供不同的 UI 表现，
二来方便语义上的理解，使 ”只读数据“ 和 ”可变状态“ 有着明确的区分，引导团队人员遵循 ”唯一可信源“ 或者说 ”单向数据流“ 的开发理念，规避消息同步不一致等不可预期的错误。
