### ISSUE TITLE
获取结果没有双向无感知

### ISSUE THREAD

**Issue by iopa152** [KunMinX/Jetpack-MVVM-Best-Practice#5]
返回的数据Flowable有改变没有考虑到只会刷新一次 以及UI与数据层双向无感知 databing 有部分问题 切入性大

**Comment by KunMinX** [comment]
@iopa152 
I don't quite understand what you mean. 
If it is from machine translation, it is better to speak English directly.
不太明白你的意思，如果是机翻的话，不如直接说英文。
在 Jetpack MVVM 的开发模式中，数据层和 UI 层是关注点分离的，
其中，Flowable 是在数据层内部消化的工作，同时也支持在执行过程中通过 liveData 发送过程消息；
DataBinding 是 UI 层的架构组件，如需双向绑定，在 xml 中为其配置好即可，与数据层无关。
