### ISSUE TITLE
MuMu模拟器上，按下home键之后再次进入应用，ObservableField和MutableLiveData失效，视图一直无法更新。

### ISSUE THREAD

**Issue by markLeeXX** [KunMinX/Jetpack-MVVM-Best-Practice#51]
![image](https://user-images.githubusercontent.com/27982416/101602158-a114b300-3a38-11eb-96d6-06c888000931.png)

通知栏状态和播放状态不一致。

**Comment by KunMinX** [comment]
@markLeeXX 

原因可能是 mumu 模拟器在界面退出时，为节省内存而直接销毁页面所致，具体可自行尝试调试，

另外，mumu 模拟器不兼容大多数软件，它是专为极少数与之合作的（游戏）厂商而生的。
