### ISSUE TITLE
为什么不适用dagger？

### ISSUE THREAD

**Issue by lwns** [KunMinX/Jetpack-MVVM-Best-Practice#53]

**Comment by KunMinX** [comment]
@lwns 
我们主要是以 ”多人协作的软件工程“ 为背景来考虑架构设计，除了解决最基本的一致性问题外，还须考虑学习成本等因素，
dagger 依赖注入框架不是每个成员都能理解和熟练运用，并且其设计打断了上下文阅读的连贯性，
故而在集体开发的项目中，不建议 dagger 的使用。个人开发请随意。
