### ISSUE TITLE
请问，所有数据来源都只会存在成功状态？

### ISSUE THREAD

**Issue by qiushui95** [KunMinX/Jetpack-MVVM-Best-Practice#6]
不管来自网络还是apk内部。既然写的是最佳实践，应该需要异常处理

**Comment by KunMinX** [comment]
@qiushui95 
那你很屌哦。

不管异不异常，我们都会将电线埋入地下，而不会任其暴露在地表绊到或电到他人。

我们把对 网络状态 的管理封装到基类里，并静默输送回 视图控制器的基类由其统一处理 网络状态 UI 逻辑。

具体可参考 NetworkStateManager。
