### ISSUE TITLE
【探讨】关于依赖注入的使用

### ISSUE THREAD

**Issue by painld6** [KunMinX/Jetpack-MVVM-Best-Practice#72]
在 readme 中看到有一项说绝不使用 Dagger，但对于 jetpack 中的 hilt，请问怎么看。。。后续会加到这个项目中吗？看了官方文档，感觉 hilt 的使用相比 Dagger 方便很多，又减少了一部分样板代码，还是挺不错的，1.0.0 正式版也已经发布了

**Comment by KunMinX** [comment]
@painld6 

依赖注入我们通常用于模块化开发背景下，领域层对数据层的访问，你想在项目中使用的话，可以自行 fork 源码和尝试引入。
