### ISSUE TITLE
ViewDataBinding 不暴露给实现Activity问题

### ISSUE THREAD

**Issue by wingdi** [KunMinX/Jetpack-MVVM-Best-Practice#73]
ViewDataBinding 不暴露给实现Activity问题

比如xml中定义的TabItem，它的onClick事件无法通过databinding实现，如果用了会报空指针异常。。 这时就要在自己实现的Acitivity中 取到TabItem  ， 对它进行点击事件处理

**Comment by KunMinX** [comment]
@wingdi 
如果公司项目允许 kotlin，我们建议您使用 koltin + viewBinding 的组合来代替 DataBinding，前者是更优解，后者是不得已，二者效果等同，但前者的使用门槛更低、更符合惯用的思维。

**Comment by wingdi** [comment]
好的谢谢，但愿 kotlin+viewBinding 是最最最后解了，折腾不玩了，kotlin又有协程 dagger这些新技术
