### ISSUE TITLE
大佬有没有room结合livedata 和ViewModel的案例推荐的？

### ISSUE THREAD

**Issue by wowo3129** [KunMinX/Jetpack-MVVM-Best-Practice#8]
大佬有没有room结合livedata 和ViewModel的案例推荐的？

**Comment by KunMinX** [comment]
@wowo3129 
room 配合 mvvm 架构的使用其实很简单。

在 DataRepository 中创建一个 本地数据源接口，然后创建一个基于 Room 的 Manager 去实现这个接口，在 DataRepository 中完成业务逻辑的处理，并最终通过 liveData 将结果通知给 UI 层即可。
