### ISSUE TITLE
请教个livedata机制问题

### ISSUE THREAD

**Issue by bannerkun** [KunMinX/Jetpack-MVVM-Best-Practice#9]
使用了room配合livedata处理数据变动，一有数据变更就反馈到ui层，这没错，有时候一条数据某些值要变动，或者收到服务器传递过来的数据，需要修改相同的数据，会传递2次以上到ui导致adapter重复添加数据到界面上这种是要通过减少相同数据操作，还是ui上数据处理，还是把livedata换成一个子类M开头的。感觉表达起来有点问题，其实我就是想问相同数据操作数据库引起的重复通知更新，大神你是怎么处理的。

**Comment by KunMinX** [comment]
@bannerkun  
根据你的描述，我判定 你真正要解决的是 确立唯一可信源，即，项目中需要确保数据的来源只有一处，而不是多处。

任何数据的改动，都要向数据源发起请求，并通过唯一可信源来统一通知所有 UI 界面的变动。

可以考虑将 本地数据源和 远程数据源，统一交给 DataRepository 来管理和分发结果。

此外，添加数据 和 修改数据，应分别交给不同业务中不同的 liveData 来推送，从而在视图控制器中在不同的 liveData Observe 中分别做相应的 UI 处理。

**Comment by bannerkun** [comment]
@KunMinX  有看过谷歌架构建议，如果处理本地数据源和远程数据源，会造成开发成本高，复杂，我现在的做法是远程数据直接存在本地数据库，本地数据库再通过ui变更。后面一点 添加数据 修改数据 这一块倒是没想到还可以这么做，我觉得还是没get到我的点，多次修改数据库，返回多次多个重复的集合数据，这一块要怎么处理，给adpter。

**Comment by KunMinX** [comment]
@bannerkun 
本人拥有三年的架构实践经验，你提到的这个问题，在我看来完全是一目了然、毫无疑问的。

添加数据就是添加数据，修改数据就是修改数据，这两种业务应完全隔离、采取两套不同的业务和 UI 逻辑处理。
这和数据源在远程、在本地、采取策略分治，是毫无关系的。

如果你要解决的是 妥善处理重复响应给 UI 层的数据，那么就在 UI 层做好匹配处理。
再者，远程数据源和本地数据源 本来就是根据实际需要来组合分治，这和重复响应没有直接的关系。
