### ISSUE TITLE
为什么不转成kotlin

### ISSUE THREAD

**Issue by gslovemy** [KunMinX/Jetpack-MVVM-Best-Practice#92]
为什么不转成kotlin

**Comment by KunMinX** [comment]
经过我们的调研，70% 以上的公司仍在使用 java 开发或维护项目，而 java 项目又是 “null 安全一致性问题” 高发的场景，因而关于 Jetpack MVVM，我们专注且只分享 java 语言背景的案例。

kotlin 如今官方推广已有 4 年，有条件请及早上车 kotlin，以及尝试 compose 等框架。
